/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-11-23 18:49:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\" />\r\n");
      out.write("    <title>Edit Item</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Nunito&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t<script\r\n");
      out.write("\t  src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\t  integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\t  crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t    src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <div class=\"signUpContainer\">\r\n");
      out.write("      <h1>Inventory management System</h1>\r\n");
      out.write("      <form class=\"signUpForm\" id=\"editItem\" action=\"FrontController\" method=\"post\">\r\n");
      out.write("        <h1 class=\"formHeading\">Edit Item</h1>\r\n");
      out.write("        <input type=\"hidden\" name=\"itemid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemName\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"text\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item name\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemDesc\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"text\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item Description\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemPrice\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"number\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item Price\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemQuantity\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"number\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item Quantity\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemCategory\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"text\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item Category\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"input\"\r\n");
      out.write("          name=\"itemSupplier\"\r\n");
      out.write("          size=\"18\"\r\n");
      out.write("          type=\"text\"\r\n");
      out.write("          value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.itemSupplier}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("          placeholder=\"Item Supplier\"\r\n");
      out.write("        />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"loginFormButtons\">\r\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"UpdateItem\" />\r\n");
      out.write("          <input class=\"button\" type=\"submit\" value=\"Update\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#editItem\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("            \titemName: \"required\",\r\n");
      out.write("                itemDesc: \"required\",\r\n");
      out.write("                itemPrice: \"required\",\r\n");
      out.write("                itemQuantity: \"required\",\r\n");
      out.write("                itemCategory: \"required\",\r\n");
      out.write("                itemSupplier: \"required\",\r\n");
      out.write("            },\r\n");
      out.write("             \r\n");
      out.write("            messages: {\r\n");
      out.write("            \titemName: \"Name of the Item is required\",\r\n");
      out.write("                itemDesc: \"Description of item is required\",\r\n");
      out.write("                itemPrice: \"Price of item is required\",\r\n");
      out.write("                itemQuantity: \"Quantity of item is required\",\r\n");
      out.write("                itemCategory: \"Category of item is required\",\r\n");
      out.write("                itemSupplier: \"Supplier of item is required\",\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /editItem.jsp(21,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("item");
    // /editItem.jsp(21,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/editItem.jsp(21,4) '${sessionScope.item}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.item}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
